# Generated by Django 4.1.3 on 2023-02-02 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvedleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empidforleave', models.CharField(max_length=100)),
                ('dateofleave', models.DateField(default=django.utils.timezone.now)),
                ('reasonofleave', models.CharField(max_length=200)),
                ('approved_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='requestleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empidforleave', models.CharField(max_length=100)),
                ('dateofleave', models.DateField(default=django.utils.timezone.now)),
                ('reasonofleave', models.CharField(max_length=200)),
                ('inperson_charge', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
