# Generated by Django 4.1.3 on 2023-02-02 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_employee_phone_hr_phone_manager_phone_qdmin_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid_for_report', models.CharField(max_length=100)),
                ('doucment_overview', models.FileField(upload_to='report_fils')),
                ('submit_date', models.DateField(default=django.utils.timezone.now)),
                ('compliction_status', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
    ]
