# Generated by Django 4.1.3 on 2023-02-03 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0007_alter_approvedleave_dateofleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('employee_score', models.IntegerField(default=0)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(max_length=200)),
                ('skills', models.CharField(max_length=100)),
                ('c_w_p', models.CharField(default='company', max_length=100)),
                ('request_by', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapp.manager')),
            ],
        ),
    ]
