# Generated by Django 4.1.3 on 2023-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0008_request_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_employee',
            name='photo',
            field=models.ImageField(upload_to='empphoto/'),
        ),
    ]
