# Generated by Django 4.1.3 on 2023-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0009_alter_request_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='emphoto'),
        ),
    ]
