# Generated by Django 4.1.3 on 2023-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0010_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(upload_to='emphoto'),
        ),
    ]
