# Generated by Django 4.1.3 on 2023-02-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0011_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='qdmin',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='request_employee',
            name='photo',
        ),
    ]
