# Generated by Django 4.1.3 on 2023-02-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0012_remove_employee_photo_remove_hr_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_employee',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
