# Generated by Django 4.1.3 on 2023-02-06 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0013_alter_request_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='req_hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('req_by', models.CharField(default='own', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='req_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('req_by', models.CharField(default='own', max_length=100)),
            ],
        ),
    ]
